source "https://rubygems.org"

ruby "2.1.2"

gem "coffee-rails", "~> 4.0.0"
gem "dotenv-rails"
gem "jbuilder", "~> 2.0"
gem "jquery-rails"
gem "monban", "~> 0.1.0"
gem "neat"
gem "newrelic_rpm"
gem "pg"
gem "pusher"
gem "rails", "4.1.4"
gem "rails_12factor"
gem "rails_autolink"
gem "sass-rails", "~> 4.0.3"
gem "uglifier", ">= 1.3.0"
gem "unicorn"
